pipeline {
    agent any

    stages {
        stage('Stage1') {
            steps {
                echo 'Hello this is the first stage.'
            }
        }
        stage('Stage2') {
            steps {
                echo 'This is the second stage.'
            }
        }
    }
}
